// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs9eTfzsAtG7ocOgCSW6R3muNq-_d3388',
    appId: '1:186318079556:web:74aae05018ff2dca551e11',
    messagingSenderId: '186318079556',
    projectId: 'nusantaradelight-8712b',
    authDomain: 'nusantaradelight-8712b.firebaseapp.com',
    storageBucket: 'nusantaradelight-8712b.appspot.com',
    measurementId: 'G-QJD6YJQ2TX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIlVutcyTlpCxJqYby-dCh23MMghgx2Pg',
    appId: '1:186318079556:android:4ce5e17f9ce36221551e11',
    messagingSenderId: '186318079556',
    projectId: 'nusantaradelight-8712b',
    storageBucket: 'nusantaradelight-8712b.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs9eTfzsAtG7ocOgCSW6R3muNq-_d3388',
    appId: '1:186318079556:web:c07f99fc104e8b88551e11',
    messagingSenderId: '186318079556',
    projectId: 'nusantaradelight-8712b',
    authDomain: 'nusantaradelight-8712b.firebaseapp.com',
    storageBucket: 'nusantaradelight-8712b.appspot.com',
    measurementId: 'G-3CHF69ZMKW',
  );
}
